# Generated by Django 4.1.6 on 2023-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0002_alter_alquiler_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alquiler_images'),
        ),
    ]
